# Generated by Django 4.2.17 on 2025-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0002_event_student_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='', max_length=15, null=True, unique=True),
        ),
    ]
