# Generated by Django 4.2.17 on 2025-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0003_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
