# Generated by Django 4.2.16 on 2025-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0004_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('onstage', 'On-stage'), ('offstage', 'Off-stage')], default='offstage', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
