# Generated by Django 4.2.16 on 2025-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0005_event_category_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='', max_length=15, null=True, unique=True),
        ),
    ]
